Repository mas-cli/mas, pull requests merged in 2025-04, with the labels that each got.

#734 Improve `script/test` boilerplate filtering for newer `swift` executables.
  .swift-format
  Brewfile
  Tests/masTests/.swift-format
  script/format
  script/lint
  script/test
  script/version
Labels: 🧽 chore

#736 Upgrade Nimble to 13.7.1 & Quick to 7.6.2
  Package.resolved
  Package.swift
  Tests/masTests/Commands/AccountSpec.swift
  Tests/masTests/Commands/HomeSpec.swift
  Tests/masTests/Commands/InfoSpec.swift
  Tests/masTests/Commands/InstallSpec.swift
  Tests/masTests/Commands/ListSpec.swift
  Tests/masTests/Commands/LuckySpec.swift
  Tests/masTests/Commands/OpenSpec.swift
  Tests/masTests/Commands/OutdatedSpec.swift
  Tests/masTests/Commands/PurchaseSpec.swift
  Tests/masTests/Commands/SearchSpec.swift
  Tests/masTests/Commands/SignInSpec.swift
  Tests/masTests/Commands/SignOutSpec.swift
  Tests/masTests/Commands/UninstallSpec.swift
  Tests/masTests/Commands/UpgradeSpec.swift
  Tests/masTests/Commands/VendorSpec.swift
  Tests/masTests/Commands/VersionSpec.swift
  Tests/masTests/Controllers/ITunesSearchAppStoreSearcherSpec.swift
  Tests/masTests/Formatters/AppListFormatterSpec.swift
  Tests/masTests/Formatters/SearchResultFormatterSpec.swift
  Tests/masTests/Models/SearchResultListSpec.swift
  Tests/masTests/Models/SearchResultSpec.swift
  Tests/masTests/Models/SoftwareProductSpec.swift
Labels: 🧽 chore, 📚 dependencies, 🧪 testing

#737 Use Swift Concurrency instead of PromiseKit
  Package.resolved
  Package.swift
  Sources/mas/AppStore/Downloader.swift
  Sources/mas/AppStore/ISStoreAccount.swift
  Sources/mas/AppStore/PurchaseDownloadObserver.swift
  Sources/mas/AppStore/SSPurchase.swift
  Sources/mas/Commands/Account.swift
  Sources/mas/Commands/Home.swift
  Sources/mas/Commands/Info.swift
  Sources/mas/Commands/Install.swift
  Sources/mas/Commands/Lucky.swift
  Sources/mas/Commands/Open.swift
  Sources/mas/Commands/Outdated.swift
  Sources/mas/Commands/Purchase.swift
  Sources/mas/Commands/Search.swift
  Sources/mas/Commands/SignIn.swift
  Sources/mas/Commands/Upgrade.swift
  Sources/mas/Commands/Vendor.swift
  Sources/mas/Controllers/AppStoreSearcher.swift
  Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
  Sources/mas/MAS.swift
  Sources/mas/Models/SearchResult.swift
  Sources/mas/Network/NetworkManager.swift
  Sources/mas/Network/NetworkSession.swift
  Sources/mas/Network/URL.swift
  Sources/mas/Network/URLSession+NetworkSession.swift
  Tests/masTests/Commands/AccountSpec.swift
  Tests/masTests/Commands/HomeSpec.swift
  Tests/masTests/Commands/InfoSpec.swift
  Tests/masTests/Commands/InstallSpec.swift
  Tests/masTests/Commands/ListSpec.swift
  Tests/masTests/Commands/LuckySpec.swift
  Tests/masTests/Commands/OpenSpec.swift
  Tests/masTests/Commands/OutdatedSpec.swift
  Tests/masTests/Commands/PurchaseSpec.swift
  Tests/masTests/Commands/SearchSpec.swift
  Tests/masTests/Commands/SignInSpec.swift
  Tests/masTests/Commands/SignOutSpec.swift
  Tests/masTests/Commands/UninstallSpec.swift
  Tests/masTests/Commands/UpgradeSpec.swift
  Tests/masTests/Commands/VendorSpec.swift
  Tests/masTests/Commands/VersionSpec.swift
  Tests/masTests/Controllers/ITunesSearchAppStoreSearcherSpec.swift
  Tests/masTests/Controllers/MockAppStoreSearcher.swift
  Tests/masTests/Formatters/AppListFormatterSpec.swift
  Tests/masTests/Formatters/SearchResultFormatterSpec.swift
  Tests/masTests/Models/SearchResultListSpec.swift
  Tests/masTests/Models/SearchResultSpec.swift
  Tests/masTests/Models/SoftwareProductSpec.swift
  Tests/masTests/Network/MockFromFileNetworkSession.swift
  Tests/masTests/Utilities/Consequences.swift
Labels: 🧽 chore, 📚 dependencies

#740 Obtain installed apps from Spotlight
  .swiftlint.yml
  Sources/mas/AppStore/CKSoftwareMap+SoftwareMap.swift
  Sources/mas/Commands/Install.swift
  Sources/mas/Commands/List.swift
  Sources/mas/Commands/Lucky.swift
  Sources/mas/Commands/Outdated.swift
  Sources/mas/Commands/Purchase.swift
  Sources/mas/Commands/Uninstall.swift
  Sources/mas/Commands/Upgrade.swift
  Sources/mas/Controllers/SoftwareMap.swift
  Sources/mas/Controllers/SoftwareMapAppLibrary.swift
  Sources/mas/Controllers/SpotlightSoftwareMap.swift
  Sources/mas/Models/SimpleSoftwareProduct.swift
  Tests/masTests/.swiftlint.yml
  Tests/masTests/Commands/OutdatedSpec.swift
  Tests/masTests/Commands/UninstallSpec.swift
  Tests/masTests/Formatters/AppListFormatterSpec.swift
  Tests/masTests/Models/MockSoftwareProduct.swift
  Tests/masTests/Models/SoftwareProductSpec.swift
Labels: 🐛 bug

#741 Case-insensitively sort installed apps by app name
  Sources/mas/Controllers/SoftwareMapAppLibrary.swift
Labels: 🆕 feature request

#743 Check for Quick & Nimble updates in dependabot
  .github/dependabot.yml
Labels: 🧽 chore, 📚 dependencies, 🧪 testing

#747 Fix installed app displayed names
  Sources/mas/Controllers/SpotlightSoftwareMap.swift
Labels: 🐛 bug, 🖨 output

#749 Downgrade Quick to 7.5.0 to fix multi-architecture executable build bug in Quick 7.6.0+
  Package.resolved
  Package.swift
Labels: 🐛 bug, 📚 dependencies

#752 Do not prepend any branch prefix to the version if the main branch does not exist
  script/version
Labels: 🐛 bug, 🧽 chore

#754 Ignore major & minor updates for Quick in Dependabot
  .github/dependabot.yml
Labels: 🧽 chore

#756 Improve `*AppStoreSearcher` DocC
  Sources/mas/Controllers/AppStoreSearcher.swift
  Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
Labels: 🧽 chore

#758 Improve `*AppLibrary` DocC
  Sources/mas/Controllers/AppLibrary.swift
  Sources/mas/Controllers/SoftwareMapAppLibrary.swift
Labels: 🧽 chore

#760 Fix app installation output
  Sources/mas/AppStore/PurchaseDownloadObserver.swift
  Sources/mas/AppStore/SSPurchase.swift
Labels: 🐛 bug, 🖨 output

#763 Enable Dependabot checks for Quick
  .github/dependabot.yml
Labels: 🧽 chore

#767 When upgrading apps, don't short circuit when encountering any app ID that is unknown to the MAS
  Sources/mas/Commands/Upgrade.swift
  Sources/mas/Controllers/SoftwareMapAppLibrary.swift
Labels: 🐛 bug

#771 Improve concurrency & other cleanup
  Package.resolved
  Package.swift
  Sources/mas/AppStore/CKSoftwareProduct+SoftwareProduct.swift
  Sources/mas/AppStore/Downloader.swift
  Sources/mas/AppStore/PurchaseDownloadObserver.swift
  Sources/mas/AppStore/SSPurchase.swift
  Sources/mas/Commands/Config.swift
  Sources/mas/Commands/Install.swift
  Sources/mas/Commands/Lucky.swift
  Sources/mas/Commands/Outdated.swift
  Sources/mas/Commands/Purchase.swift
  Sources/mas/Commands/Uninstall.swift
  Sources/mas/Commands/Upgrade.swift
  Sources/mas/Controllers/SpotlightSoftwareMap.swift
  Sources/mas/Formatters/AppListFormatter.swift
  Sources/mas/Formatters/Utilities.swift
  Sources/mas/Models/SoftwareProduct.swift
Labels: 🧹 cleanup

#776 Code cleanup
  .swiftlint.yml
  Sources/mas/AppStore/CKSoftwareProduct+SoftwareProduct.swift
  Sources/mas/AppStore/Downloader.swift
  Sources/mas/AppStore/PurchaseDownloadObserver.swift
  Sources/mas/Commands/Account.swift
  Sources/mas/Commands/Info.swift
  Sources/mas/Commands/Install.swift
  Sources/mas/Commands/Lucky.swift
  Sources/mas/Commands/Outdated.swift
  Sources/mas/Commands/Purchase.swift
  Sources/mas/Commands/Search.swift
  Sources/mas/Commands/SignIn.swift
  Sources/mas/Commands/Upgrade.swift
  Sources/mas/Controllers/AppLibrary.swift
  Sources/mas/Controllers/SpotlightSoftwareMap.swift
  Sources/mas/Errors/MASError.swift
  Sources/mas/Formatters/AppInfoFormatter.swift
  Sources/mas/Formatters/AppListFormatter.swift
  Sources/mas/Formatters/Utilities.swift
  Sources/mas/Models/SimpleSoftwareProduct.swift
  Sources/mas/Models/SoftwareProduct.swift
  Sources/mas/Network/NetworkManager.swift
  Tests/masTests/.swiftlint.yml
  Tests/masTests/Commands/OutdatedSpec.swift
  Tests/masTests/Commands/UninstallSpec.swift
  Tests/masTests/Formatters/AppListFormatterSpec.swift
  Tests/masTests/Models/SoftwareProductSpec.swift
Labels: 🧽 chore

#779 Support apps under `/Volumes/*/Applications`
  .swiftlint.yml
  Sources/mas/AppStore/CKSoftwareMap+SoftwareMap.swift
  Sources/mas/AppStore/CKSoftwareProduct+SoftwareProduct.swift
  Sources/mas/Controllers/SpotlightSoftwareMap.swift
  Sources/mas/Models/AppID.swift
Labels: 🐛 bug

#785 Reenable `account` for macOS 11-
  Sources/mas/AppStore/Downloader.swift
  Sources/mas/AppStore/ISStoreAccount.swift
  Sources/mas/AppStore/SSPurchase.swift
  Sources/mas/Commands/Account.swift
  Sources/mas/Commands/SignIn.swift
  Tests/masTests/Commands/AccountSpec.swift
Labels: 🐛 bug

#789 Make `SoftwareProduct` & `SimpleSoftwareProduct` immutable
  Sources/mas/Models/SimpleSoftwareProduct.swift
  Sources/mas/Models/SoftwareProduct.swift
  Tests/masTests/Commands/UninstallSpec.swift
Labels: 🧽 chore

#791 Reword "Apple ID" as "Apple Account"
  README.md
  Sources/mas/Commands/Account.swift
  Sources/mas/Commands/SignIn.swift
  Sources/mas/Commands/SignOut.swift
  Sources/mas/Errors/MASError.swift
  contrib/completion/mas.fish
Labels: 🧽 chore, 🖨 output

#793 Use `NSMetadataItem*Key` instead of `kMDItem*` for Spotlight query keys
  Sources/mas/Controllers/SpotlightSoftwareMap.swift
Labels: 🧽 chore

#798 Improve output code.
  Sources/mas/AppStore/Downloader.swift
  Sources/mas/AppStore/PurchaseDownloadObserver.swift
  Sources/mas/Commands/Install.swift
  Sources/mas/Commands/Lucky.swift
  Sources/mas/Commands/Outdated.swift
  Sources/mas/Commands/Purchase.swift
  Sources/mas/Commands/Reset.swift
  Sources/mas/Commands/Search.swift
  Sources/mas/Commands/Uninstall.swift
  Sources/mas/Commands/Upgrade.swift
  Sources/mas/Controllers/SoftwareMapAppLibrary.swift
  Sources/mas/Formatters/AppInfoFormatter.swift
  docs/sample.swift
Labels: 🧽 chore, 🖨 output

#800 Remove unused imports
  Sources/mas/AppStore/Downloader.swift
  Sources/mas/Commands/SignIn.swift
  Sources/mas/Controllers/AppLibrary.swift
  Sources/mas/Controllers/SoftwareMapAppLibrary.swift
  Sources/mas/Models/SimpleSoftwareProduct.swift
  Tests/masTests/Commands/OutdatedSpec.swift
  Tests/masTests/Commands/UninstallSpec.swift
Labels: 🧽 chore

#803 docs(known issues): explain that mas relies on mds
  README.md
Labels: 🧽 chore

#812 Improve `README.md`
  README.md
Labels: 🧽 chore

#814 Warn about how to index installed apps when no apps found by `mas list`
  Sources/mas/Commands/List.swift
  Tests/masTests/Commands/ListSpec.swift
Labels: 🆕 feature request, 🖨 output

#817 Upgrade Xcode to 16.3 on GHA macos-15 runners
  .github/workflows/build-test.yml
  .github/workflows/tag-pushed.yml
Labels: 🧽 chore

#820 Remove the homebrew-core bump step from `release-published.yml`
  .github/workflows/release-published.yml
Labels: 🧽 chore, 🍺 homebrew

#821 Remove `@retroactive`
  Sources/mas/AppStore/ISStoreAccount.swift
Labels: 🧽 chore

#824 Always install all dependencies in `Brewfile` as now only support building on macOS 13+
  Brewfile
Labels: 🧽 chore

#826 Use local time zone for `info` dates
  Sources/mas/Formatters/AppInfoFormatter.swift
Labels: 🧽 chore

#829 Improve `MASError.notSupported` description
  Sources/mas/Errors/MASError.swift
Labels: 🧽 chore, 🖨 output

#830 Improve code spacing
  .markdownlint.json
  .swiftlint.yml
  Sources/mas/Commands/Uninstall.swift
  Sources/mas/Formatters/AppListFormatter.swift
  contrib/completion/mas.fish
  script/format
  script/generate_token
  script/lint
  script/package
  script/test
Labels: 🧽 chore

#834 Do not delete the cache folder since it hasn't been used since 2021
  Sources/mas/Network/NetworkManager.swift
Labels: 🧽 chore

#835 Change package identifier from `com.mphys.mas-cli` to `io.github.mas-cli`
  script/package
Labels: 🧽 chore

#837 Simplify networking.
  Sources/mas/Controllers/ITunesSearchAppStoreSearcher.swift
  Sources/mas/Network/NetworkManager.swift
  Sources/mas/Network/NetworkSession.swift
  Sources/mas/Network/URLSession+NetworkSession.swift
  Tests/masTests/Commands/LuckySpec.swift
  Tests/masTests/Controllers/ITunesSearchAppStoreSearcherSpec.swift
  Tests/masTests/Network/MockNetworkSession.swift
Labels: 🧽 chore

#840 Only interact with apps under `/Applications` or MAS-designated large app drive
  Sources/mas/Controllers/SpotlightInstalledApps.swift
Labels: 🐛 bug

#841 Support multiple app ID & search term arguments for all relevant commands
  Sources/mas/Commands/Home.swift
  Sources/mas/Commands/Info.swift
  Sources/mas/Commands/Lucky.swift
  Sources/mas/Commands/Search.swift
  Sources/mas/Commands/Uninstall.swift
  Sources/mas/Commands/Vendor.swift
  Sources/mas/Errors/MASError.swift
  Tests/masTests/Commands/UninstallSpec.swift
Labels: 🆕 feature request

#843 Improve URL parsing error handling
  Sources/mas/Commands/Home.swift
  Sources/mas/Commands/Open.swift
  Sources/mas/Commands/Vendor.swift
  Sources/mas/Errors/MASError.swift
Labels: 🆕 feature request, 🖨 output
